version: 0.2

phases:
  install:
    commands:
      - echo Install started on `date`
      - aws cloudformation package --template-file samTemplate.yml --output-template-file outputSamTemplate.yaml --s3-bucket shoppinglist-sam-matthew.pothier
artifacts:
  type: zip
  files:
    - samTemplate.yml
    - outputSamTemplate.yaml